### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by sagamusix** [Konstanty/libmodplug#11]
"If it sounds wrong there, then send the mod and a bug report to Olivier Lapicque" - Given that Olivier has open-sourced the tracker more than 10 years ago and hasn't worked on it since then, it's probably futile to make him fix a bug in ModPlug Tracker 1.16. :) And reporting the bug to us (OpenMPT team) is of course also futile because our code has quite diverged from the original source drop. So maybe simply remove that part of the readme. :)

**Comment by mxmilkb** [comment]
I think it would also be worth mentioning libmodplugs use in other software, most notably [Mixxx](https://mixxx.org/).
